<?php
	
	$ADVT_NAME = "Classified Ads";   // Advertisement name
	$ADVT_URL = "http://www.louisvillemusic.com/advt";       // Advertisement folder URL, no trailing slash
	$IMAGE_DIR = "./image";                    // Image upload directory, no trailing slash
	                                           // A folder named '$IMAGE_DIR' in this case is 'image'
	                                           // and a sub-folder named 'thumb' must be created.
	                                           // Their permission is 777.
	/* ADMIN CONFIGURATION */
	$ADMIN_EMAIL = "admin@louisvillemusic.com";         // Admin's email
	$ADMIN_NAME = "pmarr";                      // Admin's login ID
	$ADMIN_PASS = "!!AR+ax";                      // Admin's password

	/* PAGE CONFIGURATION */
	$PAGE_BG_COLOR = "#f5e3a7";                // Page background color
	$PAGE_BG_IMAGE = "";                       // Page background image, leave blank if none
?>